/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CertificationResult {
  'workerId' : bigint,
  'level' : string,
  'issuedDate' : Time,
  'skill' : string,
  'certificateId' : string,
  'mcqScore' : bigint,
  'practicalPassed' : boolean,
  'passed' : boolean,
}
export interface LearningRequest {
  'id' : bigint,
  'message' : string,
  'timestamp' : Time,
  'requesterId' : string,
  'targetUserId' : bigint,
}
export type Time = bigint;
export interface User {
  'id' : bigint,
  'bio' : string,
  'badgeLevel' : string,
  'name' : string,
  'trustScore' : bigint,
  'endorsementCount' : bigint,
  'distance' : bigint,
  'skill' : string,
  'videoURL' : string,
  'location' : string,
}
export interface _SERVICE {
  'endorseUser' : ActorMethod<[bigint], undefined>,
  'getAllLearningRequests' : ActorMethod<[], Array<LearningRequest>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCertification' : ActorMethod<[bigint], [] | [CertificationResult]>,
  'getLearningRequestsForWorker' : ActorMethod<
    [bigint],
    Array<LearningRequest>
  >,
  'getUser' : ActorMethod<[bigint], User>,
  'getUsersByDistance' : ActorMethod<[bigint], Array<User>>,
  'getUsersBySkill' : ActorMethod<[string], Array<User>>,
  'getWorkerStats' : ActorMethod<[bigint], User>,
  'init' : ActorMethod<[], undefined>,
  'registerCitizen' : ActorMethod<[string, string], bigint>,
  'registerWorker' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'submitLearningRequest' : ActorMethod<[string, bigint, string], undefined>,
  'submitTestResult' : ActorMethod<[bigint, bigint, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];