/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const LearningRequest = IDL.Record({
  'id' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
  'requesterId' : IDL.Text,
  'targetUserId' : IDL.Nat,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'badgeLevel' : IDL.Text,
  'name' : IDL.Text,
  'trustScore' : IDL.Nat,
  'endorsementCount' : IDL.Nat,
  'distance' : IDL.Nat,
  'skill' : IDL.Text,
  'videoURL' : IDL.Text,
  'location' : IDL.Text,
});
export const CertificationResult = IDL.Record({
  'workerId' : IDL.Nat,
  'level' : IDL.Text,
  'issuedDate' : Time,
  'skill' : IDL.Text,
  'certificateId' : IDL.Text,
  'mcqScore' : IDL.Nat,
  'practicalPassed' : IDL.Bool,
  'passed' : IDL.Bool,
});

export const idlService = IDL.Service({
  'endorseUser' : IDL.Func([IDL.Nat], [], []),
  'getAllLearningRequests' : IDL.Func(
      [],
      [IDL.Vec(LearningRequest)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCertification' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CertificationResult)],
      ['query'],
    ),
  'getLearningRequestsForWorker' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LearningRequest)],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Nat], [User], ['query']),
  'getUsersByDistance' : IDL.Func([IDL.Nat], [IDL.Vec(User)], ['query']),
  'getUsersBySkill' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'getWorkerStats' : IDL.Func([IDL.Nat], [User], ['query']),
  'init' : IDL.Func([], [], []),
  'registerCitizen' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'registerWorker' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'submitLearningRequest' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'submitTestResult' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const LearningRequest = IDL.Record({
    'id' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
    'requesterId' : IDL.Text,
    'targetUserId' : IDL.Nat,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'badgeLevel' : IDL.Text,
    'name' : IDL.Text,
    'trustScore' : IDL.Nat,
    'endorsementCount' : IDL.Nat,
    'distance' : IDL.Nat,
    'skill' : IDL.Text,
    'videoURL' : IDL.Text,
    'location' : IDL.Text,
  });
  const CertificationResult = IDL.Record({
    'workerId' : IDL.Nat,
    'level' : IDL.Text,
    'issuedDate' : Time,
    'skill' : IDL.Text,
    'certificateId' : IDL.Text,
    'mcqScore' : IDL.Nat,
    'practicalPassed' : IDL.Bool,
    'passed' : IDL.Bool,
  });
  
  return IDL.Service({
    'endorseUser' : IDL.Func([IDL.Nat], [], []),
    'getAllLearningRequests' : IDL.Func(
        [],
        [IDL.Vec(LearningRequest)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCertification' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CertificationResult)],
        ['query'],
      ),
    'getLearningRequestsForWorker' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LearningRequest)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Nat], [User], ['query']),
    'getUsersByDistance' : IDL.Func([IDL.Nat], [IDL.Vec(User)], ['query']),
    'getUsersBySkill' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
    'getWorkerStats' : IDL.Func([IDL.Nat], [User], ['query']),
    'init' : IDL.Func([], [], []),
    'registerCitizen' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'registerWorker' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
    'submitLearningRequest' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'submitTestResult' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };